name: Java CI - Mini Project

on:
  push:
    paths:
      - 'week1/day7-github-action/**'
  pull_request:
    paths:
      - 'week1/day7-github-action/**'

jobs:
  build:
    runs-on: ubuntu-latest
    working-directory: week1/day7-github-action

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test
